### Records Resource

POST http://localhost:8000/records
Content-Type: application/json

{
  "data": "This is a sample record"
}

###

GET http://localhost:8000/records
Content-Type: application/json


### Queue Resource


POST http://localhost:8000/queue
Content-Type: application/json

{
  "payload": {
    "task": "run backup",
    "priority": "high"
  }
}

###

GET http://localhost:8000/queue
Content-Type: application/json


### Stream Resource


POST http://localhost:8000/stream
Content-Type: application/json

{
  "event": {
    "action": "update",
    "detail": "Event example"
  }
}

###

GET http://localhost:8000/stream
Content-Type: application/json

### Consumers Resource

GET http://localhost:8000/consumers
Content-Type: application/json


### Errors

POST http://localhost:8000/error/500
Content-Type: application/json
