services:
  example:
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 0
        delay: 10s
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
    healthcheck:
      test:
        - CMD-SHELL
        - wget -qO- --spider http://127.0.0.1:8080
      timeout: 10s
      interval: 10s
      retries: 5
      start_period: 10s
    image: registry:5000/example:${MINIPAAS_DEPLOY_VERSION}
    networks:
      minipaas_network: {}
    secrets:
      - source: postgres_password.267da420
        target: postgres_password
  example-consumer:
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 0
        delay: 10s
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
    image: registry:5000/example:${MINIPAAS_DEPLOY_VERSION}
    networks:
      minipaas_network: {}
    secrets:
      - source: postgres_password.267da420
        target: postgres_password
  example-cron:
    deploy:
      mode: replicated
      replicas: 0
      labels:
        swarm.cronjob.enable: "true"
        swarm.cronjob.schedule: '* * * * *'
        swarm.cronjob.skip-running: "true"
      restart_policy:
        condition: none
    image: registry:5000/example:${MINIPAAS_DEPLOY_VERSION}
    networks:
      minipaas_network: {}
    secrets:
      - source: postgres_password.267da420
        target: postgres_password
  example-migration:
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 0
        delay: 10s
        failure_action: pause
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
    image: registry:5000/example-migration:${MINIPAAS_DEPLOY_VERSION}
    networks:
      minipaas_network: {}
    secrets:
      - source: postgres_password.267da420
        target: postgres_password
  example-worker:
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 0
        delay: 10s
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
    image: registry:5000/example:${MINIPAAS_DEPLOY_VERSION}
    networks:
      minipaas_network: {}
    secrets:
      - source: postgres_password.267da420
        target: postgres_password
  postgres:
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 0
        delay: 10s
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
    networks:
      minipaas_network: {}
    secrets:
      - source: postgres_password.267da420
        target: postgres_password
networks:
  minipaas_network:
    name: minipaas_network
    external: true
secrets:
  postgres_password.267da420:
    external: true
