services:
  registry:
    image: "registry:${MINIPAAS_REGISTRY_IMAGE_TAG:-2}"
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - minipaas_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

volumes:
  registry_data:

