- name: Ensure Docker directory exists
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: install_certificates

- name: Copy CA certificate on API nodes
  copy:
    src: "{{ docker_tls_dir }}/ca.pem"
    dest: "/etc/docker/ca.pem"
    owner: root
    group: root
    mode: '0644'
  when: install_certificates

- name: Copy server certificate on API nodes
  copy:
    src: "{{ docker_tls_dir }}/server-cert.pem"
    dest: "/etc/docker/server-cert.pem"
    owner: root
    group: root
    mode: '0644'
  when: install_certificates

- name: Copy server key on API nodes
  copy:
    src: "{{ docker_tls_dir }}/server-key.pem"
    dest: "/etc/docker/server-key.pem"
    owner: root
    group: root
    mode: '0600'
  when: install_certificates

- name: Configure Docker API for TLS on API nodes
  copy:
    src: daemon_api.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  when: install_certificates
