- name: Ensure nftables is installed and enabled
  ansible.builtin.apt:
    name: nftables
    state: present
    update_cache: true


- name: Generate nftables configuration file
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and start nftables
  ansible.builtin.systemd:
    name: nftables
    enabled: true
    state: started
