---
- name: The main manager
  set_fact:
    is_main_manager : "{{ inventory_hostname == groups['managers'][0] }}"

- name: The main manager
  set_fact:
    is_manager : "{{ inventory_hostname in groups['managers'] }}"

- name: The main manager
  set_fact:
    is_worker : "{{ inventory_hostname in groups['workers'] }}"

- name: Whether to install the TLS for the Docker API or not
  set_fact:
    install_certificates : "{{ is_main_manager and minipaas_runtime_enabled }}"

- name: Whether to deploy MiniPaaS default runtime or not
  set_fact:
    install_runtime : "{{ is_main_manager and minipaas_runtime_enabled }}"

- name: Whether Telegram is enabled
  set_fact:
    use_telegram : "{{ telegram_chat_id and telegram_bot_token }}"

# node tools
- import_tasks: install.yml
- import_tasks: fail2ban.yml
- import_tasks: monitoring.yml
- import_tasks: syslog-ng.yml

# docker
- import_tasks: docker_conf_api.yml
- import_tasks: docker_conf_normal.yml
- import_tasks: docker.yml
- import_tasks: swarm_managers.yml
- import_tasks: swarm_ops.yml
- import_tasks: swarm_workers.yml

# docker tools
- import_tasks: cronjob.yml
- import_tasks: cronjob_disable.yml

# PaaS
- import_tasks: deploy.yml
