---
- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Restart Fail2Ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart Swarm-Cronjob
  ansible.builtin.service:
    name: swarm-cronjob
    state: restarted
