name: MiniPaaS CLI

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  test:
    runs-on: debian-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: make build

      - name: Run tests
        run: make test

  build:
    needs: test
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
        include:
          - goos: darwin
            os: macos-latest
          - goos: linux
            os: debian-latest
          - goos: windows
            os: windows-latest
            suffix: .exe
    runs-on: ${{ matrix.os }}
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Dependencies
        run: go mod tidy

      - name: Build
        run: make build WHAT=minipaas SUFFIX=${{ matrix.suffix }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/

  release:
    needs: build
    runs-on: debian-latest
    steps:
      - name: Download Linux AMD64 Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-linux-amd64

      - name: Download Windows AMD64 Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-windows-amd64

      - name: Download Darwin AMD64 Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-darwin-amd64

      - name: Release MiniPaaS CLI
        uses: softprops/action-gh-release@v2
