name: MiniPaaS Role

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  test:
    runs-on: debian-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: minipaas-role

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Lint MiniPaaS Role
        working-directory: minipaas-role
        run: ansible-lint

  release:
    runs-on: debian-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Import MiniPaaS Role to Ansible Galaxy
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
        run: ansible-galaxy role import sombrahq_bot/minipaas-role
